routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');

});
*/
//Route::get('/home', 'PagesController@home');
//Route::get('/about', 'PagesController@about');
//Route::get('/contact', 'PagesController@contact');
//Route::get('/index', 'PagesController@index');

Route::resource('/crud','PostsController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
Route::get('admin/posts/example', array('as'=>'admin.home' ,function(){

    $url = route('admin.home');

    return "This url is: ". $url;

}));
*/

Route::get('/', function()
{
    return View('pages.home');
});
Route::get('about', function()
{
    return View::make('pages.about');
});
Route::get('store', function()
{
    return View::make('pages.store');
});
Route::get('contact', function()
{
    return View::make('pages.contact');
});

Route::get('insert',function()
{
  return View::make('crud.insert');
}
)->name('insert');

Route::get('/show','PagesController@show');

Route::get('/insert_category', 'CategoriesController@create');

Route::POST('/insert_category', 'CategoriesController@store');

//*****************************************************************

/*Route::get('/', [
    'uses' => 'ProductController@getIndex',
    'as' => 'product.index'
]);*/

Route::get('/add-to-cart/{id}',[
    'uses' => 'ProductController@getAddToCart',
    'as' => 'product.addToCart'
]);

Route::get('/shopping-cart',[
    'uses' => 'ProductController@getCart',
    'as' => 'product.shoppingCart'
])->middleware('auth');

Route::get('/checkout', [
    'uses' => 'ProductController@getCheckout',
    'as' => 'checkout'
]);

Route::post('/checkout', [
    'uses' => 'ProductController@postCheckout',
    'as' => 'checkout'
]);

Route::get('/reduce/{id}', [
    'uses' => 'ProductController@getReduceByOne',
    'as' => 'product.reduceByOne'
]);
Route::get('/remove/{id}', [
    'uses' => 'ProductController@getRemoveItem',
    'as' => 'product.remove'
]);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'PC Master Race') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body style="background-color:#000000">
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top" style="background-color:#FACA04">
            <div class="container">

                <div class="navbar-header">


                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                                    <!-- Branding Image -->
                                        <a class="navbar-brand" href="{{ url('/') }}">
                                            {{ config('app.name', '') }}
                                        </a>

                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                        @include('includes.header')
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                    <li>  <a href="{{ route('product.shoppingCart') }}">
                      <i class="fa fa-shopping-cart" aria-hidden="true"></i> Shopping Cart
                      <span class="badge">{{ Session::has('cart') ? Session::get('cart')->totalQty : '' }}</span></a> </li>
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>
                                        <li>
                                        <li>
                                          @if(Auth::user()->role_id==1)
                                          <li><a href="{{route('crud.create')}}">
                                            Inserir Novo Produto
                                              </a>
                                          </li>
                                          <li><a href="/insert_category">
                                            Inserir Nova Categoria
                                          </a>
                                          </li>
                                          <li><a href="/crud">
                                            Lista Produtos
                                          </a>
                                          </li>
                                          @endif
                                        </li>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @yield('content')
    </div>
    <footer class="row">
        @include('includes.footer')
    </footer>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/default.blade.php
<!doctype html>
<html>
<head>
    @include('includes.head')
</head>
<body>
<div class="container">

    <header class="row">
        @include('includes.header')
    </header>

    <div id="main" class="row">

            @yield('content')

    </div>

    <footer class="row">
        @include('includes.footer')
    </footer>

</div>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<!doctype html>
<html>
<head>
    @include('includes.head')
</head>
<body>
<div class="container">

    <header class="row">
        @include('includes.header')
    </header>

    <div id="main" class="row">

        <!-- sidebar content -->
        <div id="sidebar" class="col-md-4">
            @include('includes.sidebar')
        </div>

        <!-- main content -->
        <div id="content" class="col-md-8">
            @yield('content')
        </div>

    </div>

    <footer class="row">
        @include('includes.footer')
    </footer>

</div>
</body>
</html>